copyright: Copyright &copy; 2022 Daniel Alencar Penha Carvalho

# Site
site_name: MongoDB
site_url: https://github.com/GkingOficial/MongoDB
site_author: Talisson Cardoso Damião

# Repository
repo_name: GkingOficial/MongoDB
repo_url: https://github.com/GkingOficial/MongoDB

# Style
theme:
  name: material
  language: pt
  logo: assets/mongodb-logo.png

  # Features
  features:
    - content.code.annotate # allow add simple markers within block/inline comments
    # - content.tabs.link         # make content tabs on a page be linked
    - navigation.instant # instant reloading
    - navigation.tracking # url in the address bar automatically updated with the active anchor
    # - navigation.sections       # top-level sections rendered as groups
    # - navigation.expand         # feft sidebar expand all collapsible subsections by default
    - navigation.top # back-to-top button
    # - header.autohide           # header automatically hidden
    - navigation.indexes # documents can be directly attached to sections (not working properly!)
    # - navigation.tabs           # top-level sections rendered in menu
    - navigation.tabs.sticky # lock sections in menu
    - search.highlight # highlight all occurrences of word searched
    # - search.share              # shareble link to current query search
    - search.suggest # search display the likeliest completion for the last word
    # - toc.integrate             # toc rendered as part of the navigation

  # Colors
  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Trocar para Modo Escuro
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Trocar para Modo Claro

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/talisson-damiao/
    - icon: fontawesome/brands/github
      link: https://github.com/GkingOficial

nav:
  - Início: index.md
  - Sobre o Autor: about.md
  - Introdução ao MongoDB:
      - Sobre o MongoDB: 1 - Introdução ao MongoDB/Sobre o MongoDB.md
      - Instalação do MongoDB: 1 - Introdução ao MongoDB/Manual de instalação do MongoDB.md
      - Instalação do MongoDB Compass: 1 - Introdução ao MongoDB/Manual de instalação do MongoDB Compass.md
  - Execução e CRUD MongoDB:
      - Execução e CRUD MongoDB: 2 - Execução e CRUD MongoDB/Execução e CRUD MongoDB.md
  - Utilizando MongoDB com Python:
      - Utilizando MongoDB com Python: 3 - Utilizando MongoDB com Python/Utilizando MongoDB com Python.md
  - Exercícios MongoDB:
      - Exercícios MongoDB: 4 - Exercícios MongoDB/Exercícios MongoDB.md
